version: '3'

services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-docker-container
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=property_management_db
      - MYSQL_USER=db_tech_user
      - MYSQL_PASSWORD=Initial1
    #restart: always
  property-management-container:
    container_name: property-management-container
    image: property-management-image:latest
    #restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql-container

    
